// List of skills
const skillKeywords = [
    "C++",
    "CPP",
    "JavaScript",
    "React",
    "Node.js",
    "MongoDB",
    "Python",
    "CSS",
    "Next JS",
    "Express Js",
    "MERN",
    "Angular",
    "HTML",
    "SQL",
    "Java",
    "C#",
    "Ruby",
    "PHP",
    // "Go",
    "Swift",
    "Kotlin",
    "Rust",
    "Haskell",
    "Scala",
    "Elixir",
    "Clojure",
    "Perl",
    // "R",
    "MATLAB",
    "Julia",
    "Lisp",
    "MySQL",
    "PostgreSQL",
    "Oracle",
    "SQL Server",
    "SQLite",
    "Cassandra",
    "Redis",
    "Couchbase",
    "Elasticsearch",
    "Neo4j",
    "AWS RDS",
    "Azure SQL Database",
    "GCP Cloud SQL",
    "AWS",
    "Azure",
    "GCP",
    "DigitalOcean",
    "Heroku",
    "EC2",
    // "S3",
    "Lambda",
    "Cloud Functions",
    "Kubernetes",
    "Docker",
    "Cloud Storage",
    "BigQuery",
    "Cloud Firestore",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Jenkins",
    "CircleCI",
    "Travis CI",
    "Ansible",
    "Terraform",
    "Puppet",
    "CI/CD",
    "UI",
    "UX",
    "DevOps",
    "Infrastructure as Code (IaC)",
    "iOS",
    "Swift",
    "Objective-C",
    "Android",
    "Java",
    "Kotlin",
    "React Native",
    "Flutter",
    "Xcode",
    "Android Studio",
    "NumPy",
    "Pandas",
    "Matplotlib",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Jupyter Notebook",
    "RStudio",
    "Kaggle",
    "Design patterns",
    "Algorithms",
    "Data structures",
    "Cybersecurity",
    "Penetration testing",
    "Cryptography",
    "User experience",
    "User interface",
    "Agile",
    "Scrum",
    "Waterfall",
    "Unit testing",
    "Integration testing",
    "QA",
    "Data science",
    "Machine learning",
    "Artificial intelligence",
    "Natural language processing",
    "Computer vision",
    "Blockchain",
    "Web development",
    "Backend development",
    "Frontend development",
    "Full-stack development",
    "Mobile app development",
    "Database management",
    "Cloud engineering",
    "DevOps engineering",
    "Software engineering",
    "Quality assurance",
    "Project management",
    "UI/UX design",
    "Cybersecurity",
    "Data analysis",
    "Data visualization",
    "Software testing",
    "Network engineering",
    "Systems engineering",
    "Information technology",
    "Information systems",
    "Computer science",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Adobe Premiere Pro",
    "Adobe After Effects",
    "Adobe Animate",
    "Figma",
    "Sketch",
    "Canva",
    "CorelDRAW",
    "GIMP",
    "Blender",
    "Unity",
    "Unreal Engine",
    "Maya",
    "Cinema 4D",
    "ZBrush",
    "Substance Painter",
    "3D modeling",
    "Animation",
    "Game development",
    "Motion graphics",
    "Video editing",
    "Graphic design",
    "UI/UX design",
    "Visual communication",
    "Digital art",
    "Illustration",
    "Typography",
    "Color theory",
    "Design principles",
    "User experience design",
    "User interface design",
    "Interaction design",
    "Information architecture",
    "Visual storytelling",
    "Brand identity",
    "Logo design",
    "Web design",
    "Print design",
    "Packaging design",
    "Motion design",
    "Animation",
    "Visual effects",
    "3D animation",
    "2D animation",
    "Character animation",
    "Stop-motion animation",
    "Game design",
    "Level design",
    "Game development",
    "Game engine programming",
    "Game art",
    "Game audio",
    "Game testing",
    "Game balancing",
    "Game mechanics",
    "Game theory",
    "Communication",
    "Time Management",
    "Problem Solving",
    "Adaptability",
    "Teamwork",
]
// Function to extract skills from text
const extractSkills = (text) => {
    const lowerText = text.toLowerCase() // Convert text to lowercase
    const foundSkills = new Set()

    // Loop through the list of skills and check if each one is mentioned in the text
    skillKeywords.forEach((skill) => {
        if (lowerText.includes(skill.toLowerCase())) {
            // Case-insensitive matching
            foundSkills.add(skill)
        }
    })

    return foundSkills // Return the array with all found skills
}

export { extractSkills }
